### ISSUE TITLE
Manuális kód átvizsgálás és statikus analízis eszköz futtatása és jelzett hibák átnézése

### ISSUE THREAD

**Issue by nagymarci98** [BME-MIT-IET/iet-hf2021-aranyaszok#3]

**Comment by gaalgery** [comment]
A kódban a nagyobb hibák javítva lettek, amiket a SonarLint jelzett. Ezen kívül a maven segítségével összekötöttük a repo-t a SonarCloud-al, így a kód átvizsgálása folyamatosan és automatikusan megtörténik.
