### ISSUE TITLE
Egységtesztek készítése, kódlefedettségnek mérése

### ISSUE THREAD

**Issue by nagymarci98** [BME-MIT-IET/iet-hf2021-aranyaszok#7]
Egységtesztek készítése/kiegészítése (xUnit...) + tesztek kódlefedettségének mérése és ez alapján tesztkészlet bővítése (JaCoCo, OpenCover, Coveralls, Codecov.io...)

**Comment by gaalgery** [comment]
A modell működésének teszteléséhez 18 db teszt készült, ami a maven futtat.
